version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: mongo
    command: ["--replSet","rs0","--bind_ip_all"]
    ports:
      - "27017:27017"     # kiri=host(port PC kamu), kanan=port di container
    volumes:
      - ./mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping').ok"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s

  mongors-init:
    image: mongo:7
    depends_on:
      mongo:
        condition: service_healthy
    restart: "no"
    entrypoint: >
      bash -lc "
      mongosh --host mongo:27017 --eval
      'rs.initiate({_id:\"rs0\",members:[{_id:0,host:\"mongo:27017\"}]})'
      || true
      "
